name: Python Tests

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/python-ci.yml"

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.py"
      - ".github/workflows/python-ci.yml"

jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
      - name: Lint, format, and type-check
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 --config=.flake8 .
          black --check .
          isort --check-only .
          # Run type checker in CI such that type errors can be identified and gradually addressed.
          # Once all existing type errors are addressed, the `|| echo` after the mypy call can be removed.
          mypy src || echo "Type errors found, continuing build..."
      - name: Check docstring coverage
        run: |
          interrogate -mvp sycret/ -f 52.5
      - name: Scan for security issues
        run: |
          bandit -r sycret -ll
      - name: Run tests
        run: |
          pytest test
